version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - stage1_data:/var/lib/mysql
      - ./db.cnf:/etc/mysql/conf.d/db.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aifigomysql123
      MYSQL_DATABASE: auto_checkout
      MYSQL_USER: root
      MYSQL_PASSWORD: aifigomysql123
    ports:
      - "33306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis
    container_name: lte_redis
    restart: always
    command: redis-server --requirepass aifigoredis@123
    ports:
      - "33307:6379"
    volumes:
      - stage1_redis:/data

  web:
    build: ../.
#    image: registry.cn-shanghai.aliyuncs.com/aifichina/lte_stage1:1.0
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - TZ=Asia/Shanghai
      - ENV=prod
#    command: gunicorn --workers=2 --bind=0.0.0.0:8000 ltebackendstage01.wsgi:application
    restart: always
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  migration:
    build: ../.
    environment:
      - ENV=prod

    command:
        - /bin/sh
        - -c
        - |
          python manage.py collectstatic --noinput
          python manage.py migrate
          python manage.py makemigrations
          python manage.py migrate
          echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'aifigo@123')" | python manage.py shell

    depends_on:
      - db
      - web

volumes:
  stage1_data:
  my.cnf:
  stage1_redis: